### ISSUE TITLE
Split out README into subfolders with categories

### ISSUE THREAD

**Issue by jzabroski** [natemcmaster/dotnet-tools#143]
@natemcmaster This repository is fantastic.  Especially for a librarian junkie like me.  However, .NET Core is getting so popular I wonder if things should be broken out differently?

Some possible starter categories

- Testing
- Documentation System
- Cryptography / Hashing / Compression
  - dotnet-encrypto
  - dmd5
  - dotnet-hash
  - srihash
- Project System
- Web
- Other

**Comment by natemcmaster** [comment]
I agree this list is getting a bit long. I like the idea of categories.

I've also been wondering if we should shorten each entry to a single line and a link the nuget.org page. Nuget.org already provides links to source code and project sites, and installation instructions.

**Comment by jzabroski** [comment]
@natemcmaster Thanks for your patience while I catch up on all the many projects I contribute to!

I like the examples in-line.  It motivates me to play around with new things.  There is value in telescoping information for users.  Let's start by refactoring to categories and if we still think it's hectic, we can shorten.  But I feel shortening prematurely is harder to revert than going in smaller steps.

**Comment by natemcmaster** [comment]
Not planning on doing this. Would take a lot of time to categorize on my own.

**Comment by jzabroski** [comment]
Makes sense.
