### ISSUE TITLE
Add entry for xamarin-android-binderator

### ISSUE THREAD

**Issue by dminta** [natemcmaster/dotnet-tools#184]
**Command:** `xamarin-android-binderator`

**Description:** An engine to generate Xamarin Binding projects from Maven repositories with a JSON config and razor templates.

**Project site:** [GitHub](https://github.com/Redth/Xamarin.AndroidBinderator)
**Author:** [@Redth](https://github.com/Redth)

<code>dotnet tool install -g [Xamarin.AndroidBinderator.Tool](https://www.nuget.org/packages/Xamarin.AndroidBinderator.Tool/)</code>

**Comment by natemcmaster** [comment]
This is a wiki-style repo. Please sent a pull-request to add this content.
