### ISSUE TITLE
Add NuLink

### ISSUE THREAD

**Issue by shocklateboy92** [natemcmaster/dotnet-tools#202]
[NuLink](https://github.com/nwheels-io/NuLink) which is trying to be like a `npm link` for `nuget` seems like a good candidate to be included in this list.

**Comment by natemcmaster** [comment]
Feel free to send a pull request to add it

**Comment by shocklateboy92** [comment]
Sure thing! Let me just go check with the maintainer first

**Comment by natemcmaster** [comment]
Closing as I'm not planning to do this myself. Pull requests gladly accepted to this list. It doesn't matter to me if the maintainer approves the list addition or not. As far as I'm concerned, if their tool is public there is no reason to exclude it from this list.
