### ISSUE TITLE
Please add aspnetcore-codegenerator

### ISSUE THREAD

**Issue by SleepyDeb** [natemcmaster/dotnet-tools#29]
You miss this official tool :D

NuGet:
[https://www.nuget.org/packages/dotnet-aspnet-codegenerator/](https://www.nuget.org/packages/dotnet-aspnet-codegenerator/)

To install:
`dotnet tool install --global dotnet-aspnet-codegenerator --version 2.1.1`

https://github.com/aspnet/Announcements/issues/303

**Comment by natemcmaster** [comment]
Feel free to make a pull request :)
