### ISSUE TITLE
Add ReportGenerator

### ISSUE THREAD

**Issue by latop2604** [natemcmaster/dotnet-tools#34]
ReportGenerator is as globaltool in prerelease state

See issue https://github.com/danielpalme/ReportGenerator/issues/112
And Nuget https://www.nuget.org/packages/dotnet-reportgenerator-globaltool

**Comment by natemcmaster** [comment]
I'm okay adding these to the list, even if the tool is in pre-release. I'm assuming the authors want as much visibility and feedback as possible, right?

Feel free to send a PR to add it to the list :)

**Comment by latop2604** [comment]
I will try to send a PR later.
I'm not related to the author. I just found it and it was the missing piece to have full xplat coverage report (with coverlet).

**Comment by natemcmaster** [comment]
Cool. I did a scan a while ago on github to find tools  to seed this list.
My rule is - if it’s on nuget.org, it’s  fair game to be on this list. It’s
too bad nuget doesn’t filter on package type yet.
